repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.2.0
  hooks:
  - id: check-added-large-files
  - id: check-json
  - id: check-yaml
- repo: https://github.com/sqlalchemyorg/zimports/
  rev: v0.5.0
  hooks:
  - id: zimports
- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
  - id: black
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2
  hooks:
  - id: flake8
- repo: https://github.com/commitizen-tools/commitizen
  rev: v2.23.0
  hooks:
  - id: commitizen
    stages: [commit-msg]